FROM public.ecr.aws/lambda/python:3.9

# Install build dependencies
RUN yum install -y gcc python3-devel

# Copy requirements.txt
COPY requirements.txt ${LAMBDA_TASK_ROOT}/

# Install Python packages
RUN pip install -r ${LAMBDA_TASK_ROOT}/requirements.txt --target "${LAMBDA_TASK_ROOT}"

# Copy function code
COPY app ${LAMBDA_TASK_ROOT}/app/
COPY lambda_handler.py ${LAMBDA_TASK_ROOT}/

# Set the CMD to your handler
CMD [ "lambda_handler.handler" ]