service: store-price-api
frameworkVersion: '4'

provider:
  name: aws
  runtime: python3.9

functions:
  api:
    handler: lambda_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements
